version: 0.2
phases:
  pre_build:
    commands:
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 804417496983.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
       - docker build -t nodejs-app .
  post_build:
    commands:
       - docker tag nodejs-app:latest 804417496983.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
       - echo "push build image to AWS ECR"
       - docker push 804417496983.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
