apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    app: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
  - name: service-port
    protocol: TCP
    port: 3000
    targetPort: http-web-svc
